# Generated by Django 6.0.6 on 2026-06-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_items", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="location",
            name="longitude",
            field=models.FloatField(),
        ),
    ]
