# Generated by Django 6.0.6 on 2026-07-23 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule_items", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduleitem",
            options={"ordering": ["-datetime"]},
        ),
        migrations.AlterField(
            model_name="scheduleitem",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedule_items",
                to="schedule_items.location",
            ),
        ),
    ]
