# Generated by Django 6.0.6 on 2026-06-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="content",
            field=models.CharField(max_length=1023),
        ),
    ]
