# Generated by Django 6.0.6 on 2026-06-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semantic_index", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semanticindex",
            name="datetime",
            field=models.DateTimeField(),
        ),
    ]
