# Generated by Django 6.0.6 on 2026-07-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("semantic_index", "0004_semanticindex_body_semanticindex_label"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semanticindex",
            options={"ordering": ["-datetime"]},
        ),
    ]
