# Generated by Django 6.0.6 on 2026-08-05 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semantic_index", "0005_alter_semanticindex_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semanticindex",
            name="label",
            field=models.IntegerField(
                choices=[(0, "Meta descriptor"), (1, "Body")], default=0
            ),
        ),
    ]
