# Generated by Django 6.0.6 on 2026-06-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("semantic_index", "0003_alter_semanticindex_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="semanticindex",
            name="body",
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="semanticindex",
            name="label",
            field=models.IntegerField(
                choices=[(0, "Meta descriptor"), (1, "Transcript")], default=0
            ),
        ),
    ]
