# Generated by Django 6.0.6 on 2026-08-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0002_alter_voice_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="person_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True when voice is manually confirmed as belonging to the attached person",
            ),
        ),
    ]
