# Generated by Django 6.0.6 on 2026-08-26 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0009_attachmentcontent_attribution_and_more"),
        ("people", "0003_voice_person_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="voice",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attachments.attachment",
            ),
        ),
    ]
