# Generated by Django 6.0.6 on 2026-09-03 06:36

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_voice_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voice",
            name="voice_embedding",
            field=pgvector.django.vector.VectorField(dimensions=192),
        ),
    ]
