# Generated by Django 6.0.6 on 2026-06-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schedule_items", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("json", models.JSONField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=511)),
                ("source", models.URLField(max_length=511)),
                (
                    "schedule_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="schedule_items.scheduleitem",
                    ),
                ),
            ],
        ),
    ]
