# Generated by Django 6.0.6 on 2026-06-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0002_alter_attachment_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="content",
            field=models.CharField(max_length=102300),
        ),
    ]
