# Generated by Django 6.0.6 on 2026-07-23 15:24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0004_alter_attachment_published_at"),
    ]

    operations = [
        VectorExtension(),
        migrations.AlterModelOptions(
            name="attachment",
            options={"ordering": ["-published_at"]},
        ),
        migrations.CreateModel(
            name="AttachmentContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField()),
                ("ordering", models.FloatField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=384)),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="attachments.attachment",
                    ),
                ),
            ],
        ),
    ]
