# Generated by Django 6.0.6 on 2026-08-05 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0005_alter_attachment_options_attachmentcontent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmentcontent",
            options={"ordering": ["-id", "ordering"]},
        ),
    ]
