# Generated by Django 6.0.6 on 2026-08-22 10:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0006_alter_attachmentcontent_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentcontent",
            name="voice_embedding",
            field=pgvector.django.vector.VectorField(dimensions=256, null=True),
        ),
    ]
