# Generated by Django 6.0.6 on 2026-08-23 02:42

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0007_attachmentcontent_voice_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentcontent",
            name="voice_embedding",
            field=pgvector.django.vector.VectorField(
                default=None, dimensions=256, null=True
            ),
        ),
    ]
