# Generated by Django 6.0.6 on 2026-08-26 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0008_alter_attachmentcontent_voice_embedding"),
        ("people", "0003_voice_person_confirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentcontent",
            name="attribution",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="attachmentcontent",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.voice",
            ),
        ),
    ]
