# Generated by Django 6.0.6 on 2026-09-03 06:36

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0009_attachmentcontent_attribution_and_more"),
        ("people", "0005_alter_voice_voice_embedding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachmentcontent",
            options={"ordering": ["attachment", "ordering"]},
        ),
        migrations.AlterField(
            model_name="attachmentcontent",
            name="attribution",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contents",
                to="people.person",
            ),
        ),
        migrations.AlterField(
            model_name="attachmentcontent",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contents",
                to="people.voice",
            ),
        ),
        migrations.AlterField(
            model_name="attachmentcontent",
            name="voice_embedding",
            field=pgvector.django.vector.VectorField(
                default=None, dimensions=192, null=True
            ),
        ),
    ]
