# Generated by Django 6.0.6 on 2026-09-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0010_alter_attachmentcontent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentcontent",
            name="attribution_confirmed",
            field=models.BooleanField(
                default=False,
                help_text="True when attribution is manually confirmed as belonging to the attached person",
            ),
        ),
    ]
